version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - restore_cache:
          keys:
            - v1-api-data-{{ epoch }}
            - v1-api-data-
      - run: npm run update game accounts export
      - save_cache:
          paths:
            - api/data
          key: v1-api-data-{{ epoch }}

      - run: npm run build
      - run: npm run export
      - run: npm run deploy --  --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  commit:
    jobs:
      - build
  deploy:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0,0 * * * *"
          filters:
            branches:
              only:
                - master
